version: 2.1
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install prettier
      - run:
          name: Run Lint
          command: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - lint
